name: Publish Release

on:
  release:
    types: [published]

jobs:
  build-frontend-static:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_dashboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and Build Dashboard
        run: |
          npm install
          npm run build
          
      - name: Zip Dashboard Build
        run: zip -r dashboard-build.zip .next/

      - name: Upload Dashboard Build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: web_dashboard/dashboard-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-python-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install build twine

      - name: Build Source Archive
        run: |
          python -m build --sdist

      - name: Upload Source Archive to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
